# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\xiaoluo\Desktop\研究生电子竞赛资料\TEST\ui_source.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_param = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_param.setGeometry(QtCore.QRect(370, 170, 421, 191))
        self.tableWidget_param.setObjectName("tableWidget_param")
        self.tableWidget_param.setColumnCount(5)
        self.tableWidget_param.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        item.setFont(font)
        self.tableWidget_param.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_param.setHorizontalHeaderItem(4, item)
        self.label_tile = QtWidgets.QLabel(self.centralwidget)
        self.label_tile.setGeometry(QtCore.QRect(140, 20, 551, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        font.setItalic(False)
        self.label_tile.setFont(font)
        self.label_tile.setObjectName("label_tile")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 390, 411, 151))
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(220, 40, 170, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_type = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_type)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_num = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_num)
        self.label_preview_time = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_preview_time.setObjectName("label_preview_time")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_preview_time)
        self.lineEdit_preview_time = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_preview_time.setObjectName("lineEdit_preview_time")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_preview_time)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(10, 30, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_show_frame = QtWidgets.QLabel(self.widget)
        self.label_show_frame.setGeometry(QtCore.QRect(90, 40, 91, 21))
        self.label_show_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_frame.setObjectName("label_show_frame")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_show_dealframe = QtWidgets.QLabel(self.widget)
        self.label_show_dealframe.setGeometry(QtCore.QRect(90, 70, 91, 21))
        self.label_show_dealframe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_dealframe.setObjectName("label_show_dealframe")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_show_time = QtWidgets.QLabel(self.widget)
        self.label_show_time.setGeometry(QtCore.QRect(90, 100, 91, 21))
        self.label_show_time.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show_time.setObjectName("label_show_time")
        self.label_show = QtWidgets.QLabel(self.centralwidget)
        self.label_show.setGeometry(QtCore.QRect(30, 170, 331, 191))
        self.label_show.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.label_zero = QtWidgets.QLabel(self.centralwidget)
        self.label_zero.setGeometry(QtCore.QRect(20, 10, 101, 91))
        self.label_zero.setText("")
        self.label_zero.setObjectName("label_zero")
        self.lcdNumber_time = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_time.setGeometry(QtCore.QRect(640, 90, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_time.setFont(font)
        self.lcdNumber_time.setStyleSheet("color: rgb(78, 104, 255);")
        self.lcdNumber_time.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_time.setDigitCount(8)
        self.lcdNumber_time.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_time.setObjectName("lcdNumber_time")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(470, 500, 91, 41))
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(14)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("color: rgb(0, 255, 0);")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(670, 500, 91, 41))
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(14)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.radioButton_save = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_save.setGeometry(QtCore.QRect(570, 420, 81, 31))
        self.radioButton_save.setObjectName("radioButton_save")
        self.pushButton_saveimage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveimage.setGeometry(QtCore.QRect(670, 400, 101, 61))
        font = QtGui.QFont()
        font.setFamily("楷体_GB2312")
        font.setPointSize(14)
        self.pushButton_saveimage.setFont(font)
        self.pushButton_saveimage.setObjectName("pushButton_saveimage")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(470, 440, 75, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(470, 400, 75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setDefaultUp(True)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_quit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_param.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_param.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_param.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_param.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_param.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_param.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget_param.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget_param.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "疵点结果"))
        item = self.tableWidget_param.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "疵点类型"))
        item = self.tableWidget_param.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "图像"))
        self.label_tile.setText(_translate("MainWindow", "基于深度学习的嵌入式机器视觉智能检测系统"))
        self.label_9.setText(_translate("MainWindow", "检测信息："))
        self.label_7.setText(_translate("MainWindow", "疵点类型"))
        self.label_8.setText(_translate("MainWindow", "疵点编号"))
        self.label_preview_time.setText(_translate("MainWindow", "预览时间"))
        self.label_3.setText(_translate("MainWindow", "采集帧数："))
        self.label_show_frame.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "处理帧数："))
        self.label_show_dealframe.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "处理时间："))
        self.label_show_time.setText(_translate("MainWindow", "0"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_quit.setText(_translate("MainWindow", "退出"))
        self.radioButton_save.setText(_translate("MainWindow", "自动保存"))
        self.pushButton_saveimage.setText(_translate("MainWindow", "保存图像"))
        self.pushButton_reset.setText(_translate("MainWindow", "停止预览"))
        self.pushButton_save.setText(_translate("MainWindow", "开启预览"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

